-- 0017_taxonomy.sql
-- AI-skill taxonomy that drives Tier 2 classification + the public methodology
-- page. Slugs are referenced from nav_postings.llm_categories (jsonb) so they
-- MUST be immutable — enforced by a trigger below. To rename a category, mark
-- the old one retired_at and create a new slug.
--
-- Public read so /metode can render the taxonomy directly from the DB
-- (same pattern as keywords). Staff can edit via /admin/categories (PR 7).
--
-- Idempotent.

create table if not exists public.taxonomy_categories (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  definition_md text not null default '',
  sort_order int not null default 0,
  retired_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.taxonomy_versions (
  version int primary key generated by default as identity,
  created_at timestamptz not null default now(),
  notes text
);

drop trigger if exists taxonomy_categories_updated_at on public.taxonomy_categories;
create trigger taxonomy_categories_updated_at
  before update on public.taxonomy_categories
  for each row execute function public.trigger_set_updated_at();

-- Slug immutability. Verification step 10 in the plan: even a direct PATCH
-- via PostgREST must be blocked.
create or replace function public.taxonomy_categories_slug_immutable()
  returns trigger as $$
begin
  if NEW.slug is distinct from OLD.slug then
    raise exception 'taxonomy_categories.slug is immutable; create a new row with retired_at set on the old one instead'
      using errcode = 'check_violation';
  end if;
  return NEW;
end
$$ language plpgsql;

drop trigger if exists taxonomy_categories_slug_immutable on public.taxonomy_categories;
create trigger taxonomy_categories_slug_immutable
  before update on public.taxonomy_categories
  for each row execute function public.taxonomy_categories_slug_immutable();

alter table public.taxonomy_categories enable row level security;
alter table public.taxonomy_versions enable row level security;

-- Public read of live categories so /metode can render straight from the DB.
drop policy if exists taxonomy_categories_public_read on public.taxonomy_categories;
create policy taxonomy_categories_public_read on public.taxonomy_categories
  for select using (retired_at is null);

drop policy if exists taxonomy_categories_staff_read on public.taxonomy_categories;
create policy taxonomy_categories_staff_read on public.taxonomy_categories
  for select using (public.is_staff());

drop policy if exists taxonomy_categories_admin_write on public.taxonomy_categories;
create policy taxonomy_categories_admin_write on public.taxonomy_categories
  for all using (public.is_admin_or_super())
  with check (public.is_admin_or_super());

drop policy if exists taxonomy_versions_staff_read on public.taxonomy_versions;
create policy taxonomy_versions_staff_read on public.taxonomy_versions
  for select using (public.is_staff());

drop policy if exists taxonomy_versions_admin_write on public.taxonomy_versions;
create policy taxonomy_versions_admin_write on public.taxonomy_versions
  for all using (public.is_admin_or_super())
  with check (public.is_admin_or_super());

-- Seed: 5 initial categories with workable definitions. Operator refines via
-- /admin/categories (PR 7). on conflict (slug) do nothing means re-runs and
-- post-edit re-deploys are safe — definition edits via the UI survive.
insert into public.taxonomy_categories (slug, title, definition_md, sort_order) values
  (
    'prompt-engineering',
    'Prompt-engineering',
    'Stillinger som primært handler om å designe, optimalisere og forvalte instruksjoner (prompts) for store språkmodeller. Krever forståelse av prompt-mønstre, evaluering, og iterativ forbedring av modellatferd.',
    10
  ),
  (
    'ml-data-science',
    'ML / Data science',
    'Stillinger som bruker statistikk, maskinlæring og dataanalyse for å bygge prediktive modeller eller utlede innsikt fra data. Klassisk data scientist / ML researcher / applied scientist.',
    20
  ),
  (
    'ai-agent-builder',
    'AI-agentbygging',
    'Stillinger som bygger autonome AI-systemer som utfører fler-trinns oppgaver med verktøy. Inkluderer LangChain/LlamaIndex-baserte agenter, RAG-pipelines, verktøykall og orchestrering.',
    30
  ),
  (
    'ml-engineering-mlops',
    'ML-engineering / MLOps',
    'Stillinger som driver produksjonsdeployment av ML-modeller — infrastruktur, skalering, monitoring, A/B-testing, modell-serving. MLOps-orientert; mer engineering enn modellering.',
    40
  ),
  (
    'applied-ai-software',
    'Anvendt AI / programvare',
    'Programvareutvikling som integrerer AI-funksjoner i et bredere produkt. Ikke primært ML-stilling, men krever forståelse av AI-API-er, prompts eller modell-integrering.',
    50
  )
on conflict (slug) do nothing;

-- Seed first taxonomy version. Idempotent guard so re-runs don't keep
-- inserting new versions. Subsequent versions are bumped by /admin/categories
-- on meaningful taxonomy edits (PR 7).
do $seed_v1$
begin
  if not exists (select 1 from public.taxonomy_versions) then
    insert into public.taxonomy_versions (notes) values ('initial bootstrap');
  end if;
end $seed_v1$;
