-- 0073_bruk_responses.sql
-- Schema for the 5th Kibarometer pillar: /bruk — a self-reported map of how
-- Norwegians use AI. First public-write surface in the codebase: anonymous
-- visitors submit a survey + email, confirm via magic link, and we publish
-- aggregate stats. No buying-intent questions; this pillar stays journalistic.
--
-- See plan: i-want-to-continue-unified-yeti.md, PR 1 + PR 2.
--
-- Idempotent.

create extension if not exists citext;

-- ---------------------------------------------------------------------------
-- bruk_responses — the survey table
-- ---------------------------------------------------------------------------
-- Lifecycle: 'pending' → 'confirmed' (magic-link clicked) → optionally
-- 'deleted' (self-serve via delete token, or admin override). Expired pending
-- rows are swept by the bruk-refresh-stats cron after 30 days.
--
-- Tokens are stored as sha256 hashes; the plaintext only ever exists in the
-- generated magic-link URL emailed to the user. Same pattern as password
-- hashing — a DB leak doesn't let an attacker confirm anyone.

create table if not exists public.bruk_responses (
  id                  bigint primary key generated by default as identity,
  email               citext not null,
  status              text not null check (status in (
                        'pending','confirmed','expired','deleted'
                      )),
  -- Q1: 'privatperson' or a taxonomy_categories.slug
  q1_bransje          text not null,
  -- Q2: usage frequency
  q2_frequency        text not null check (q2_frequency in (
                        'daglig','ukentlig','av-og-til','proevd-ikke-regelmessig','aldri'
                      )),
  -- Q3: AI tools used (multi-select, null when Q2='aldri')
  q3_tools            text[],
  -- Q4: use cases (multi-select, null when Q2='aldri')
  q4_use_cases        text[],
  -- Q5: workplace AI policy (null when Q1='privatperson')
  q5_workplace_policy text,
  -- Tokens are sha256(plaintext); plaintext lives only in the emailed URL.
  confirm_token_hash  bytea,
  delete_token_hash   bytea,
  token_expires_at    timestamptz,
  submitted_at        timestamptz not null default now(),
  confirmed_at        timestamptz,
  -- Forensics-only hashes (never exported, never publicly displayed).
  user_agent_hash     bytea,
  ip_hash             bytea,
  send_attempts       smallint not null default 0,
  last_send_error     text,
  raw_jsonb           jsonb
);

-- Element-level + cross-column check constraints, added via do-blocks so the
-- migration is safe to re-run after the constraints already exist.
do $constraints$ begin
  if not exists (select 1 from pg_constraint where conname = 'bruk_q3_tools_valid') then
    alter table public.bruk_responses add constraint bruk_q3_tools_valid
      check (q3_tools is null or q3_tools <@ array[
        'chatgpt','claude','gemini','copilot','perplexity','lokal','andre','vil-ikke-svare'
      ]::text[]);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'bruk_q4_use_cases_valid') then
    alter table public.bruk_responses add constraint bruk_q4_use_cases_valid
      check (q4_use_cases is null or q4_use_cases <@ array[
        'skriving','soek','oppsummering','koding','oversettelse','laering',
        'idemyldring','bildegen','dataanalyse','underholdning','annet'
      ]::text[]);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'bruk_q5_policy_valid') then
    alter table public.bruk_responses add constraint bruk_q5_policy_valid
      check (q5_workplace_policy is null or q5_workplace_policy in (
        'sanksjonert','tolerert','uklart','fraraadet','vet-ikke'
      ));
  end if;
  -- Drop the misleading bruk_q1_valid constraint if it exists from an
  -- earlier dev run. It only checked length>0 which is no stronger than
  -- the NOT NULL on the column; the trigger below does the real validation
  -- against taxonomy_categories. Keeping it would give false confidence
  -- to anyone reading the schema. Idempotent — does nothing on fresh DBs.
  alter table public.bruk_responses drop constraint if exists bruk_q1_valid;
  if not exists (select 1 from pg_constraint where conname = 'bruk_q3_q4_skip_when_aldri') then
    -- "Aldri" respondents must skip Q3 and Q4; non-"aldri" respondents must
    -- answer them. Equivalence enforced as a single check.
    alter table public.bruk_responses add constraint bruk_q3_q4_skip_when_aldri
      check ((q2_frequency = 'aldri') = (q3_tools is null and q4_use_cases is null));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'bruk_q5_skip_when_private') then
    -- Privatperson respondents skip Q5; bransje respondents must answer.
    alter table public.bruk_responses add constraint bruk_q5_skip_when_private
      check ((q1_bransje = 'privatperson') = (q5_workplace_policy is null));
  end if;
end $constraints$;

-- Trigger to enforce Q1 references a live taxonomy slug (when not
-- 'privatperson'). This catches typos and bad submissions at insert time.
create or replace function public.bruk_responses_q1_check()
  returns trigger as $$
begin
  if NEW.q1_bransje = 'privatperson' then
    return NEW;
  end if;
  if not exists (
    select 1 from public.taxonomy_categories tc
    where tc.slug = NEW.q1_bransje and tc.retired_at is null
  ) then
    raise exception 'bruk_responses.q1_bransje % is not a live taxonomy slug', NEW.q1_bransje
      using errcode = 'check_violation';
  end if;
  return NEW;
end
$$ language plpgsql;

-- Scoped to insert + column-level update of q1_bransje so status-flip PATCHes
-- (e.g., the magic-link confirm path setting status='confirmed') don't
-- re-run the validation. q1_bransje is never updated post-insert in any of
-- our flows, but if an operator retires a taxonomy slug between submit and
-- confirm, an unscoped trigger would block the confirmation with a
-- check_violation. The validation still runs on every fresh INSERT and on
-- any explicit UPDATE of q1_bransje (e.g., admin re-classification).
drop trigger if exists bruk_responses_q1_check on public.bruk_responses;
create trigger bruk_responses_q1_check
  before insert or update of q1_bransje on public.bruk_responses
  for each row execute function public.bruk_responses_q1_check();

-- One active row per email. Allows resubmit after expiry/deletion (those
-- statuses fall out of the partial index predicate).
create unique index if not exists bruk_responses_email_active_uq
  on public.bruk_responses (lower(email::text))
  where status in ('pending','confirmed');

-- Token lookup indexes (partial — only the row state where the lookup
-- makes sense).
create index if not exists bruk_responses_confirm_token_idx
  on public.bruk_responses (confirm_token_hash)
  where status = 'pending';

create index if not exists bruk_responses_delete_token_idx
  on public.bruk_responses (delete_token_hash)
  where status = 'confirmed';

-- ---------------------------------------------------------------------------
-- RLS — first anon-INSERT surface in the codebase
-- ---------------------------------------------------------------------------
-- Anon can INSERT into 'pending' state only. Server-side actions go through
-- the service role for the upsert + confirm + delete paths; the anon policy
-- is defense-in-depth so direct PostgREST writes can't bypass our validation.
-- Anon never SELECTs from bruk_responses — public reads go through the
-- aggregate snapshot table below.

alter table public.bruk_responses enable row level security;

drop policy if exists bruk_anon_insert on public.bruk_responses;
create policy bruk_anon_insert on public.bruk_responses
  for insert to anon with check (
    status = 'pending'
    and confirmed_at is null
    and confirm_token_hash is null
    and delete_token_hash is null
    and send_attempts = 0
  );

drop policy if exists bruk_staff_read on public.bruk_responses;
create policy bruk_staff_read on public.bruk_responses
  for select using (public.is_staff());

drop policy if exists bruk_admin_write on public.bruk_responses;
create policy bruk_admin_write on public.bruk_responses
  for all using (public.is_admin_or_super())
  with check (public.is_admin_or_super());

-- ---------------------------------------------------------------------------
-- bruk_aggregate_snapshot — the public surface
-- ---------------------------------------------------------------------------
-- Refreshed every 15 minutes by the bruk-refresh-stats cron. Public-read RLS;
-- this is the only table the marketing site (and the /api/v1/bruk/snapshot
-- endpoint) ever reads from.
--
-- Cut/bucket shape:
--   overall          / all                → total confirmed count
--   by_q1_bransje    / <slug|privatperson> → respondents per sector
--   by_q2_frequency  / <enum>             → frequency donut
--   by_q3_tool       / <enum>             → tool share (non-summing, via unnest)
--   by_q4_use_case   / <enum>             → use-case share (non-summing)
--   by_q5_policy     / <enum>             → workplace policy donut
--   by_q1_q2_heatmap / <slug>:<freq>      → sector × frequency cells

create table if not exists public.bruk_aggregate_snapshot (
  cut             text not null,
  bucket          text not null,
  confirmed_count int  not null,
  share_pct       numeric(5,2),
  computed_at     timestamptz not null default now(),
  primary key (cut, bucket)
);

alter table public.bruk_aggregate_snapshot enable row level security;

drop policy if exists bruk_snapshot_public_read on public.bruk_aggregate_snapshot;
create policy bruk_snapshot_public_read on public.bruk_aggregate_snapshot
  for select using (true);

drop policy if exists bruk_snapshot_admin_write on public.bruk_aggregate_snapshot;
create policy bruk_snapshot_admin_write on public.bruk_aggregate_snapshot
  for all using (public.is_admin_or_super())
  with check (public.is_admin_or_super());

-- ---------------------------------------------------------------------------
-- refresh_bruk_aggregate_snapshot() — called by the bruk-refresh-stats cron
-- ---------------------------------------------------------------------------
-- Single transaction: truncate the snapshot, recompute every cut from
-- confirmed responses, sweep expired pending rows. Idempotent and safe to
-- call manually from /admin/bruk.
--
-- Cut/bucket shape produced:
--   ('overall', 'all', total_confirmed_count, NULL)
--   ('by_q1_bransje', <slug|'privatperson'>, count, share_pct)
--   ('by_q2_frequency', <enum>, count, share_pct)
--   ('by_q3_tool', <enum>, count, share_pct_of_all_confirmed)
--   ('by_q4_use_case', <enum>, count, share_pct_of_all_confirmed)
--   ('by_q5_policy', <enum>, count, share_pct_of_bransje_respondents)
--   ('by_q1_q2_heatmap', <slug>':'<freq>, count, share_pct_of_bransje)

create or replace function public.refresh_bruk_aggregate_snapshot()
  returns void
  language plpgsql
  security definer
  set search_path = public
as $$
declare
  total_confirmed int;
  bransje_confirmed int;
begin
  -- Snapshot rebuild + pending sweep in one transaction.
  delete from public.bruk_aggregate_snapshot;

  select count(*) into total_confirmed
  from public.bruk_responses where status = 'confirmed';

  select count(*) into bransje_confirmed
  from public.bruk_responses
  where status = 'confirmed' and q1_bransje <> 'privatperson';

  -- overall
  insert into public.bruk_aggregate_snapshot (cut, bucket, confirmed_count, share_pct)
  values ('overall', 'all', total_confirmed, null);

  if total_confirmed > 0 then
    -- by_q1_bransje
    insert into public.bruk_aggregate_snapshot (cut, bucket, confirmed_count, share_pct)
    select 'by_q1_bransje', q1_bransje, count(*)::int,
           round(100.0 * count(*) / total_confirmed, 2)
    from public.bruk_responses
    where status = 'confirmed'
    group by q1_bransje;

    -- by_q2_frequency
    insert into public.bruk_aggregate_snapshot (cut, bucket, confirmed_count, share_pct)
    select 'by_q2_frequency', q2_frequency, count(*)::int,
           round(100.0 * count(*) / total_confirmed, 2)
    from public.bruk_responses
    where status = 'confirmed'
    group by q2_frequency;

    -- by_q3_tool (unnest; multi-select means shares don't sum to 100%)
    insert into public.bruk_aggregate_snapshot (cut, bucket, confirmed_count, share_pct)
    select 'by_q3_tool', tool, count(*)::int,
           round(100.0 * count(*) / total_confirmed, 2)
    from public.bruk_responses, unnest(q3_tools) as tool
    where status = 'confirmed' and q3_tools is not null
    group by tool;

    -- by_q4_use_case (same multi-select treatment)
    insert into public.bruk_aggregate_snapshot (cut, bucket, confirmed_count, share_pct)
    select 'by_q4_use_case', uc, count(*)::int,
           round(100.0 * count(*) / total_confirmed, 2)
    from public.bruk_responses, unnest(q4_use_cases) as uc
    where status = 'confirmed' and q4_use_cases is not null
    group by uc;

    -- by_q1_q2_heatmap (bransje × frequency, bransje respondents only)
    insert into public.bruk_aggregate_snapshot (cut, bucket, confirmed_count, share_pct)
    select 'by_q1_q2_heatmap', q1_bransje || ':' || q2_frequency, count(*)::int,
           case when bransje_confirmed > 0
                then round(100.0 * count(*) / bransje_confirmed, 2)
                else null end
    from public.bruk_responses
    where status = 'confirmed' and q1_bransje <> 'privatperson'
    group by q1_bransje, q2_frequency;

    -- by_week_confirmed (weekly trend — confirmations per ISO week,
    -- bucket = first day of the ISO week as YYYY-MM-DD). Powers the
    -- trend-line chart on /bruk.
    insert into public.bruk_aggregate_snapshot (cut, bucket, confirmed_count, share_pct)
    select 'by_week_confirmed',
           to_char(date_trunc('week', confirmed_at)::date, 'YYYY-MM-DD'),
           count(*)::int,
           null
    from public.bruk_responses
    where status = 'confirmed' and confirmed_at is not null
    group by date_trunc('week', confirmed_at)
    order by 1;
  end if;

  if bransje_confirmed > 0 then
    -- by_q5_policy (only bransje respondents have a Q5 value)
    insert into public.bruk_aggregate_snapshot (cut, bucket, confirmed_count, share_pct)
    select 'by_q5_policy', q5_workplace_policy, count(*)::int,
           round(100.0 * count(*) / bransje_confirmed, 2)
    from public.bruk_responses
    where status = 'confirmed' and q5_workplace_policy is not null
    group by q5_workplace_policy;
  end if;

  -- Sweep: expire/discard pending rows older than 30 days.
  delete from public.bruk_responses
  where status = 'pending' and submitted_at < now() - interval '30 days';
end
$$;

revoke all on function public.refresh_bruk_aggregate_snapshot() from public, anon;
grant execute on function public.refresh_bruk_aggregate_snapshot() to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- Methodology placeholder
-- ---------------------------------------------------------------------------
-- Real Norwegian prose written in PR 2 / edited via /admin/content/docs-bruk.
-- Seeded with on conflict do nothing so re-runs don't clobber edits.

insert into public.site_content (slug, title, body_md) values (
  'docs-bruk',
  'Metode — Bruk',
  E'## Metode\n\nDenne siden beskriver hvordan vi måler AI-bruk i Norge gjennom selvrapportering.\n\n## Skjevhet\n\nDataene er ikke et representativt utvalg av Norges befolkning. Respondenter har selv valgt å registrere seg, og kommer disproporsjonalt fra grupper som er interessert i AI. Tall fra denne siden bør siteres som kohortstudie, ikke populasjonsstudie.\n'
) on conflict (slug) do nothing;
